# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            blog.vi-kan.net
tagline:          'One thought after another'
description:      'Some random notes. Mostly related to code.'
url:              http://blog.vi-kan.net

author:
  name:           'Vegar Vikan'
  url:            https://twitter.com/format71

paginate:         5

# Custom vars
version:          2.0.0

clicky_site_id:   148688
google_site_id:   'UA-271278-3'

github:
  repo:           https://github.com/poole/lanyon

twitter_user:     '@format71'
